### ISSUE TITLE
Getting Broken Pipe error while running "grantmcconnaughey/lintly-flake8-github-action@v1.0"

### ISSUE THREAD

**Issue by usama2490** [grantmcconnaughey/lintly-flake8-github-action#17]
Here's an actual code snippet of the above error!

`Traceback (most recent call last):
  File "/usr/local/bin/lintly", line 5, in <module>
    from lintly.cli import main
  File "/usr/local/lib/python3.7/site-packages/lintly/cli.py", line 7, in <module>
    from .builds import LintlyBuild
  File "/usr/local/lib/python3.7/site-packages/lintly/builds.py", line 14, in <module>
    from .backends.github import GitHubBackend
  File "/usr/local/lib/python3.7/site-packages/lintly/backends/__init__.py", line 1, in <module>
    from .github import GitHubBackend  # noqa
  File "/usr/local/lib/python3.7/site-packages/lintly/backends/github.py", line [11](https://github.com/usama2490/actions-testing/runs/5830830293?check_suite_focus=true#step:4:11), in <module>
    from lintly.formatters import (
  File "/usr/local/lib/python3.7/site-packages/lintly/formatters.py", line 6, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/local/lib/python3.7/site-packages/jinja2/__init__.py", line [12](https://github.com/usama2490/actions-testing/runs/5830830293?check_suite_focus=true#step:4:12), in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/jinja2/filters.py", line [13](https://github.com/usama2490/actions-testing/runs/5830830293?check_suite_focus=true#step:4:13), in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe`

Any clues?

**Comment by jpfeuffer** [comment]
same here

**Comment by usama2490** [comment]
@jpfeuffer , there's an issue with the versioning.. You can use my forked branch's fix to get it working into your action like this: 
**- uses: usama2490/lintly-flake8-github-action@v1.1**  until it gets an upstream fix. Hope it helps!
