### ISSUE TITLE
Getting this error while send back lint errors to PR

### ISSUE THREAD

**Issue by raudra** [grantmcconnaughey/lintly-flake8-github-action#8]
Traceback (most recent call last):
  File "/usr/local/bin/lintly", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/lintly/cli.py", line 74, in main
    build.execute()
  File "/usr/local/lib/python3.7/site-packages/lintly/builds.py", line 82, in execute
    self.submit_to_pr(patch)
  File "/usr/local/lib/python3.7/site-packages/lintly/builds.py", line 151, in submit_to_pr
    self.submit_pr_review(patch, pr_review_action)
  File "/usr/local/lib/python3.7/site-packages/lintly/builds.py", line 167, in submit_pr_review
    pr_review_action
  File "/usr/local/lib/python3.7/site-packages/lintly/backends/github.py", line 222, in create_pull_request_review
    client.post(url, data, headers={'Accept': GITHUB_API_PR_REVIEW_HEADER})
  File "/usr/local/lib/python3.7/site-packages/lintly/backends/github.py", line 82, in post
    return self._do_request('post', url, json.dumps(data), headers)
  File "/usr/local/lib/python3.7/site-packages/lintly/backends/github.py", line 114, in _do_request
    raise GitClientError(response.content, status_code=response.status_code)
lintly.backends.errors.GitClientError: b'{\n  "message": "Server Error"\n}\n'

**Comment by grantmcconnaughey** [comment]
Is this still happening? "Server Error" suggests that GitHub was down at the time this ran.
